version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deploysight
    ports:
      - "5432:5432"